import { existsSync, readdirSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { DEFAULT_HEALTH_CONFIG, DEFAULT_INSIGHTS_CONFIG, DEFAULT_OUTAGE_CONFIG } from '@campus/shared';
import type { Db } from './connection';
// Generated by build-function.mjs for serverless bundles; empty for normal builds.
import { EMBEDDED_MIGRATIONS } from './migrations.generated';

/** Arbitrary constant: serialises concurrent migrators (e.g. several cold-starting functions). */
const MIGRATION_LOCK = 724_310_001;

export function migrationsDir(): string {
  const override = process.env.MIGRATIONS_DIR;
  if (override) return override;
  const candidates = [
    path.resolve(__dirname, '../../../migrations-postgres'), // src/infrastructure/db
    path.resolve(__dirname, '../migrations-postgres'), // dist/
    path.resolve(__dirname, 'migrations-postgres'),
  ];
  return candidates.find((c) => existsSync(c)) ?? candidates[0]!;
}

function loadMigrations(dir: string): Array<{ name: string; sql: string }> {
  const embedded = EMBEDDED_MIGRATIONS;
  if (Object.keys(embedded).length) return Object.keys(embedded).sort().map((name) => ({ name, sql: embedded[name]! }));
  return readdirSync(dir)
    .filter((f) => /^\d{3}_.*\.sql$/.test(f))
    .sort()
    .map((name) => ({ name, sql: readFileSync(path.join(dir, name), 'utf8') }));
}

/**
 * Applies NNN_name.sql files from migrations-postgres/ in order, each in its own transaction,
 * tracked in `schema_migrations`. Idempotent and safe to run from several processes at once.
 * Then makes sure the default settings rows exist. Returns the names applied by this call.
 */
export async function migrate(db: Db, dir = migrationsDir()): Promise<string[]> {
  const applied: string[] = [];
  await db.transaction(async () => {
    await db.query('SELECT pg_advisory_xact_lock($1)', [MIGRATION_LOCK]);
    await db.query(`CREATE TABLE IF NOT EXISTS schema_migrations (name TEXT PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`);
    const { rows } = await db.query<{ name: string }>('SELECT name FROM schema_migrations');
    const done = new Set(rows.map((r) => r.name));
    for (const m of loadMigrations(dir)) {
      if (done.has(m.name)) continue;
      await db.query(m.sql);
      await db.query('INSERT INTO schema_migrations(name) VALUES ($1)', [m.name]);
      applied.push(m.name);
    }
    const now = new Date().toISOString();
    const insert = (key: string, value: unknown) =>
      db.query('INSERT INTO settings(key, value_json, updated_at) VALUES ($1, $2, $3) ON CONFLICT (key) DO NOTHING', [key, JSON.stringify(value), now]);
    await insert('health.config', DEFAULT_HEALTH_CONFIG);
    await insert('outage.config', DEFAULT_OUTAGE_CONFIG);
    await insert('insights.config', DEFAULT_INSIGHTS_CONFIG);
  });
  return applied;
}
